/**
 * Hevy Routines API
 * POST - Create a new routine from a generated workout
 */

import { NextRequest, NextResponse } from 'next/server';
import { getHevyConnections } from '@/lib/supabase-hevy';
import { HevyClient } from '@/lib/hevy-client';
import { GeneratedLiftingWorkout } from '@/lib/workout-generator';

const LBS_TO_KG = 0.453592;

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { workout } = body as { workout: GeneratedLiftingWorkout };

        if (!workout || !workout.exercises || workout.exercises.length === 0) {
            return NextResponse.json(
                { error: 'Invalid workout data' },
                { status: 400 }
            );
        }

        // Get the first Hevy connection (for API key)
        const connections = await getHevyConnections();
        if (connections.length === 0) {
            return NextResponse.json(
                { error: 'No Hevy connection found. Please connect Hevy first.' },
                { status: 400 }
            );
        }

        const connection = connections[0];
        const client = new HevyClient(connection.apiKey);

        // Map exercises to Hevy format
        const exercises: Array<{
            exercise_template_id: string;
            superset_id: null;
            rest_seconds: number;
            notes: string;
            sets: Array<{
                type: 'normal';
                weight_kg: number | null;
                reps: number;
            }>;
        }> = [];

        for (const ex of workout.exercises) {
            const templateId = await client.getTemplateIdByName(ex.name);

            if (templateId) {
                exercises.push({
                    exercise_template_id: templateId,
                    superset_id: null,
                    rest_seconds: 90,
                    notes: '',
                    sets: ex.sets.map(set => ({
                        type: 'normal' as const,
                        weight_kg: set.weightLbs ? Math.round(set.weightLbs * LBS_TO_KG * 10) / 10 : null,
                        reps: set.targetReps,
                    })),
                });
            } else {
                console.warn(`Could not find Hevy template for exercise: ${ex.name}`);
            }
        }

        if (exercises.length === 0) {
            return NextResponse.json(
                { error: 'Could not map any exercises to Hevy templates' },
                { status: 400 }
            );
        }

        // Add date to routine name
        const today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        const routineTitle = `${workout.name} - ${today}`;

        // Try to find or create the "Custom Routines" folder
        let folderId: string | undefined;
        try {
            const folders = await client.getRoutineFolders();
            const customFolder = folders.find(f => f.title.toLowerCase() === 'custom routines');
            if (customFolder) {
                folderId = customFolder.id;
            } else {
                // Create the folder
                const newFolder = await client.createRoutineFolder('Custom Routines');
                folderId = newFolder.id;
            }
        } catch (folderError) {
            console.warn('Could not get/create folder, creating routine without folder:', folderError);
        }

        // Create the routine
        const result = await client.createRoutine({
            title: routineTitle,
            notes: `Generated by BIA Tracker on ${new Date().toLocaleString()}`,
            folder_id: folderId,
            exercises,
        });

        return NextResponse.json({
            success: true,
            routine: result,
            exercisesMapped: exercises.length,
            exercisesSkipped: workout.exercises.length - exercises.length,
        });

    } catch (error: unknown) {
        console.error('Error creating routine:', error);
        const message = error instanceof Error ? error.message : 'Internal Server Error';
        return NextResponse.json(
            { error: message },
            { status: 500 }
        );
    }
}
